language: python

# Use container-based infrastructure
sudo: false

python:
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - python ./runtests.py
  - coverage run --source=. runtests.py
after_success:
  - coveralls
